"use client";
import { useCallback, useEffect, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { SectionId } from "@/lib/tradeos/types";
import HistoricalRecords from "./HistoricalRecords";
import ImportExportSection from "./ImportExportSection";
import { cn } from "@/lib/utils";

const steps: { title: string; description: string; section: SectionId; entities: string[]; optional?: boolean }[] = [
  { title: "Business settings and units", description: "Check your business details, currency and invoice preferences. Decide how you buy and sell: for example, one box contains 12 pieces.", section: "business-settings", entities: [] },
  { title: "Brands and categories", description: "Organize your catalog. Use consistent names so imported products link to the correct brand and category.", section: "brands", entities: ["brands", "categories"] },
  { title: "Customers and suppliers", description: "Add the people you sell to and buy from before importing transactions. Use unique names and contact details. Customer assignment is optional; importing employees does not create login accounts.", section: "customers", entities: ["customers", "suppliers"] },
  { title: "Products and opening stock", description: "Add product names, units, pack sizes and prices. Opening stock is the quantity on your chosen start date. Review reorder levels, barcode, batch and expiry settings before selling.", section: "products", entities: ["products"] },
  { title: "Historical invoices and payments", description: "Optional: bring older sales, purchases and payments into read-only history. Choose the date your current stock and balances start. Import historical invoices before payments so references can link. History will not change stock, cash or current balances; reconcile opening balances separately.", section: "sales", entities: ["historical_sales", "historical_purchases", "historical_customer_payments", "historical_supplier_payments", "customer_credit"], optional: true },
  { title: "Team and final review", description: "Optional: import your team, territories and routes. Invite employees and assign permissions separately. Check stock, balances and a sample invoice before starting daily work.", section: "staff-permissions", entities: ["employees", "staff", "territories", "routes"], optional: true },
];
const labels: Record<string, string> = { historical_sales: "Historical sales", historical_purchases: "Historical purchases", historical_customer_payments: "Historical customer payments", historical_supplier_payments: "Historical supplier payments", brands: "Brands", categories: "Categories", customers: "Customers", suppliers: "Suppliers", products: "Products", purchases: "Purchases", sales_invoices: "Sales invoices", customer_payments: "Customer payments", supplier_payments: "Supplier payments", customer_credit: "Customer credit settings", employees: "Employees", staff: "Staff records", territories: "Territories", routes: "Routes" };
const button = "min-h-11 rounded-lg border border-border bg-background px-4 py-2 text-sm font-medium hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary disabled:opacity-50";
export default function SetupImportHub({ supabase, organizationId, userId, actorProfileId, createAuditLog, onNavigate, onImported }: { supabase: SupabaseClient; organizationId: string; userId: string; actorProfileId: string | null; createAuditLog: (params: any) => Promise<void>; onNavigate: (section: SectionId) => void; onImported: () => void }) {
  const [step, setStep] = useState(0); const [reviewed, setReviewed] = useState<number[]>([]); const [counts, setCounts] = useState<Record<string, number | null>>({}); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false);
  const storageKey = `tradeos-setup-v1:${organizationId}:${userId}`;
  const [history, setHistory] = useState<{ id: string; entity_key: string; file_name: string; status: string; created_count: number; failed_count: number; started_at: string }[]>([]);
  const [historyError, setHistoryError] = useState("");
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(storageKey) || "[]"); const valid = Array.isArray(saved) ? [...new Set<number>(saved.filter(n => Number.isInteger(n) && n >= 0 && n < steps.length))] : []; setReviewed(valid); const next = steps.findIndex((_, index) => !valid.includes(index)); setStep(next < 0 ? steps.length - 1 : next); } catch { setReviewed([]); } }, [storageKey]);
  const refresh = useCallback(async () => {
    setLoading(true);
    const entries = await Promise.all(["products", "customers", "suppliers", "brands", "categories"].map(async table => {
      try { const { count, error } = await supabase.from(table).select("id", { count: "exact", head: true }).eq("organization_id", organizationId);
      return [table, error ? null : count ?? 0] as const; } catch { return [table, null] as const; }
    }));
    setCounts(Object.fromEntries(entries));
    try { const { data, error } = await supabase.from("import_exports").select("id, entity_key, file_name, status, created_count, failed_count, started_at").eq("organization_id", organizationId).eq("operation_type", "import").order("started_at", { ascending: false }).limit(10); if (error) throw error; setHistory(data ?? []); setHistoryError(""); } catch { setHistoryError("Import history could not be loaded. Refresh to try again."); }
    setLoading(false);
  }, [organizationId, supabase]);
  useEffect(() => { void refresh(); }, [refresh]);
  const markReviewed = () => { const next = [...new Set([...reviewed, step])]; setReviewed(next); try { localStorage.setItem(storageKey, JSON.stringify(next)); } catch { setNotice("Checklist progress cannot be saved in this browser. Imported records are still saved to your business account."); } if (step < steps.length - 1) setStep(step + 1); };
  return <section className="space-y-6" data-help-topic="imports">
    <header className="rounded-xl border border-border bg-card p-6"><p className="text-sm font-medium text-primary">Get your business ready</p><h1 className="mt-1 text-2xl font-semibold">Setup &amp; Data Import</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Bring your external records into TradeOS, one step at a time. Existing Import buttons and saved templates remain available in each section. Files are reviewed before saving to your business account; the import history records who performed the import.</p><p className="mt-3 text-sm">{reviewed.length} of {steps.length} steps reviewed. Checklist progress is saved on this browser for your account; record counts below come from your business data.</p><progress aria-label="Setup steps reviewed" value={reviewed.length} max={steps.length} className="mt-2 h-2 w-full" /></header>
    {notice && <p role="status" className="rounded-lg border p-3 text-sm">{notice}</p>}
    <div className="flex flex-wrap items-center gap-3">{Object.entries(counts).map(([key, count]) => <span key={key} className="rounded-lg border bg-card px-4 py-2 text-sm">{labels[key]}: <strong>{count === null ? "Unavailable" : count.toLocaleString()}</strong></span>)}<button className={button} disabled={loading} onClick={() => void refresh()}>{loading ? "Checking records…" : "Refresh counts"}</button></div>
    <div className="grid gap-5 lg:grid-cols-[260px_1fr]"><nav aria-label="Setup steps" className="space-y-2">{steps.map((item, index) => <button key={item.title} type="button" aria-current={step === index ? "step" : undefined} onClick={() => setStep(index)} className={cn(button, "w-full text-left", step === index && "border-primary bg-primary/10 text-primary")}><span className="mr-2">{reviewed.includes(index) ? "✓" : index + 1}.</span>{item.title}<span className="mt-1 block text-xs text-muted-foreground">{item.optional ? "Optional" : "Recommended setup"}</span></button>)}</nav>
    <div className="rounded-xl border border-border bg-card p-5 sm:p-6"><h2 className="text-xl font-semibold">{step + 1}. {steps[step].title}</h2><p className="my-4 text-sm leading-6 text-muted-foreground">{steps[step].description}</p>{step === 0 ? <p className="mb-5 text-sm">Open Business Settings below, check your details and save them. Then return here and mark this step reviewed.</p> : <ol className="mb-5 list-decimal space-y-2 pl-5 text-sm"><li>Choose the record type and upload CSV, Excel, ODS or Excel XML.</li><li>Load a saved template, map the columns, or ask AI for suggestions.</li><li>Review missing fields, duplicate handling and the data preview.</li><li>Confirm the import, review its results and fix any failed rows.</li></ol>}
      <div className="space-y-3">{steps[step].entities.map(entity => <div key={entity} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-4"><h3 className="font-medium">{labels[entity]}</h3><ImportExportSection entityKey={entity} entityLabel={labels[entity]} supabase={supabase} organizationId={organizationId} actorProfileId={actorProfileId} createAuditLog={createAuditLog} onImported={() => { void refresh(); onImported(); setNotice("Import finished. Review the saved records and any rejected rows before marking this step reviewed."); }} /></div>)}</div>
      <div className="mt-6 flex flex-wrap gap-3"><button className={button} onClick={() => onNavigate(steps[step].section)}>Open section / enter manually</button>{step === 2 && <button className={button} onClick={() => onNavigate("suppliers")}>Open suppliers</button>}<button className={cn(button, "border-primary bg-primary text-primary-foreground hover:bg-primary/90")} onClick={markReviewed}>Mark reviewed{step < steps.length - 1 ? " & continue" : ""}</button>{steps[step].optional && <button className={button} onClick={() => { setNotice("Optional step skipped for now. You can return any time; no data was changed."); if (step < steps.length - 1) setStep(step + 1); }}>Skip for now</button>}</div>
    </div></div>
    <HistoricalRecords organizationId={organizationId} />
    <section className="rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Recent imports</h2><p className="my-2 text-sm text-muted-foreground">The last 10 import attempts for your business. A completed attempt can still contain rejected rows; check the failed count before importing again.</p>{historyError && <p role="status">{historyError}</p>}{!historyError && !history.length && <p className="text-sm">No import attempts yet. Records entered manually are included in the counts above.</p>}<ul className="divide-y">{history.map(item => <li key={item.id} className="py-3 text-sm"><strong className="break-all">{item.file_name}</strong><p>{labels[item.entity_key] ?? item.entity_key} · {item.status} · {item.created_count ?? 0} created · {item.failed_count ?? 0} failed · {new Date(item.started_at).toLocaleString()}</p></li>)}</ul></section>
  </section>;
}
