import assert from "node:assert/strict";
import { addBarcodeLine, findBarcodeProduct, type BarcodeLine } from "../src/lib/invoices/barcode";
import { describeControl, guideTopics } from "../src/lib/help/guide";
const product = { id: "p1", name: "Test carton", barcode: "001234", unit_type: "Carton", subunit_type: "Piece", units_per_pack: 12, default_selling_price: 120, is_active: true };
assert.equal(findBarcodeProduct([product], "001234\r\n").id, "p1");
assert.throws(() => findBarcodeProduct([product], "1234"), /No active/);
assert.throws(() => findBarcodeProduct([{ ...product, is_active: false }], "001234"), /No active/);
assert.throws(() => findBarcodeProduct([product, { ...product, id: "p2" }], "001234"), /more than one/);
let lines = addBarcodeLine([], product, "subunit");
assert.equal(lines[0].selling_price, "10"); assert.equal(lines[0].quantity, "1");
lines = addBarcodeLine([{ ...lines[0], selling_price: "9" }], product, "subunit");
assert.equal(lines[0].quantity, "2"); assert.equal(lines[0].selling_price, "9");
lines = addBarcodeLine(lines, product, "main"); assert.equal(lines.length, 2); assert.equal(lines[1].selling_price, "120");
assert.equal(addBarcodeLine([], product, "subunit", { last_selling_price: 96, unit_mode: "main" })[0].selling_price, "8");
assert.equal(addBarcodeLine([], { ...product, units_per_pack: 0 }, "subunit")[0].unit_mode, "main");
const blank: BarcodeLine = { product_id: null, quantity: "", selling_price: "", discount: "", unit_mode: "main" };
assert.equal(addBarcodeLine([blank], product, "main").length, 1);
assert.equal(addBarcodeLine([{ ...blank, quantity: "3" }], product, "main").length, 2);
assert(describeControl("Units per pack").includes("12"));
assert(describeControl("Main unit").includes("main unit"));
assert(guideTopics.some(topic => topic.steps.some(step => step.includes("owner approval"))));
assert(guideTopics.length >= 10);
console.log("Barcode and guide tests passed: leading zeroes, inactive/duplicate rejection, repeated scans, main/sub-unit and recent-price conversion, edited price preservation, empty lines, tutorial guidance.");
