import assert from "node:assert/strict";
import * as XLSX from "xlsx";
import { prepareImportFile } from "../src/lib/import-export/prepare-file";
import type { ImportFieldDef } from "../src/lib/import-export/types";
const fields: ImportFieldDef[] = [{ key: "name", label: "Name", type: "text", required: true }, { key: "barcode", label: "Barcode", type: "text" }, { key: "notes", label: "Notes", type: "text" }, { key: "reorder_level", label: "Reorder", type: "number" }];
const data = prepareImportFile(["Product", "Code"], [["=not-a-formula", "00123"]], { Product: "name", Code: "barcode" }, fields);
assert.deepEqual(data.keys, ["name", "barcode"]);
assert.equal(data.incompleteRows, 0);
const sheet = XLSX.utils.aoa_to_sheet([data.keys, ...data.rows]);
assert.equal(sheet.A2.t, "s"); assert.equal(sheet.A2.f, undefined);
const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, "TradeOS Import");
const roundtrip = XLSX.read(XLSX.write(book, { type: "buffer", bookType: "xlsx" }), { type: "buffer" });
assert.equal(roundtrip.Sheets["TradeOS Import"].B2.v, "00123");
assert.throws(() => prepareImportFile(["A", "B"], [["one", "two"]], { A: "name", B: "name" }, fields), /same field/);
const missing = prepareImportFile(["Code"], [["00123"]], { Code: "barcode" }, fields);
assert.deepEqual(missing.missing, ["Name"]); assert.equal(missing.incompleteRows, 1);
assert.equal(missing.rows[0][0], "");
const preserved = prepareImportFile(["Product", "Extra"], [["Soap", "Fragile"]], { Product: "name", Extra: "__preserve_in_notes__" }, fields);
assert(preserved.rows[0].some(value => value.includes("Extra: Fragile")));
console.log("Prepared-file tests passed: mapped order, missing required values, sparse optional fields, duplicate rejection, preserved notes, leading zeroes and non-executable string cells.");

const defaults = prepareImportFile(["Code"], [["00123"]], { Code: "barcode" }, [{key:"source_system",label:"Source",type:"text",required:true,defaultValue:"External records"},{key:"barcode",label:"Barcode",type:"text"}]);
assert.equal(defaults.incompleteRows,0);assert.equal(defaults.rows[0][0],"External records");
