// TradeOS ERP — Default print templates.
//
// Each document type has one built-in default template. Users can fork a
// default into a named custom template (persisted per organization) and edit
// it with the TemplateCustomizer.

import type { PrintDocumentType, PrintTemplate } from "./print-template-types";

export const DEFAULT_PRINT_TEMPLATES: Record<PrintDocumentType, PrintTemplate> = {
  // ---------------------------------------------------------------------------
  // Sales Invoice — classic distributor invoice.
  // ---------------------------------------------------------------------------
  sales_invoice: {
    id: "default-sales-invoice",
    name: "Default Sales Invoice",
    description:
      "Classic distributor invoice: business name on top, salesman/customer/city on the left, date + invoice number on the right, product table with quantity + unit, discount column, and Grand Total / Tax / Net footer.",
    docType: "sales_invoice",
    fontFamily: "'Times New Roman', Times, serif",

    page: {
      background: "#ffffff",
      ink: "#000000",
      rule: "#000000",
    },

    header: {
      showOrgName: true,
      orgNameSizePx: 22,
      orgNamePosition: "top",
      showOrgAddress: true,
      showOrgPhone: true,
      contactSizePx: 10,
      headingText: "Sales Invoice",
      headingSizePx: 14,
      metaSizePx: 10,
      showSalesman: true,
      showCustomer: true,
      showCustomerCity: true,
      showDate: true,
      showInvoiceNo: true,
      dateLabel: "Date",
    },

    columns: {
      labels: [
        { key: "product", label: "Product", widthPct: 40 },
        { key: "quantity", label: "Quantity", widthPct: 18 },
        { key: "price", label: "Rate", widthPct: 14 },
        { key: "discount", label: "Disc", widthPct: 12 },
        { key: "total", label: "Amount", widthPct: 16 },
      ],
      headerSizePx: 9,
      rowSizePx: 10,
      uppercaseHeaders: true,
    },

    groups: {
      groupSizePx: 12,
      showPrefix: true,
      showGroupTotal: false,
      groupTotalLabel: "Total",
    },

    salesman: {
      showSalesmanSection: true,
      sizePx: 11,
      label: "Salesman",
      showSalesmanTotal: false,
      salesmanTotalLabel: "Salesman Total",
    },

    footer: {
      showTotals: true,
      labelSizePx: 11,
      valueSizePx: 12,
      totalLabel: "Grand Total",
      bonusLabel: "Discount",
      netLabel: "Net Total",
      valueSuffix: " :-",
      showFootnote: true,
      footnoteText: "Goods once sold will not be taken back. Generated by TradeOS.",
      footnoteSizePx: 8,
    },

    spacing: {
      salesmanGapPx: 12,
      groupGapPx: 8,
      rowPadYPx: 1,
    },

    boldBody: false,
  },

  // ---------------------------------------------------------------------------
  // Load Form — warehouse picking sheet grouped by salesman then brand/customer.
  // ---------------------------------------------------------------------------
  load_form: {
    id: "default-load-form",
    name: "Default Load Form",
    description:
      "Classic distributor load form: white page, black serif text, brand-grouped products, quantity shown with its unit (Cotton / Boxes), bonus, and Value/Bonus/Net footer.",
    docType: "load_form",
    fontFamily: "'Times New Roman', Times, serif",

    page: {
      background: "#ffffff",
      ink: "#000000",
      rule: "#000000",
    },

    header: {
      showOrgName: true,
      orgNameSizePx: 22,
      orgNamePosition: "top",
      showOrgAddress: true,
      showOrgPhone: true,
      contactSizePx: 10,
      headingText: "Load Form",
      headingSizePx: 14,
      metaSizePx: 10,
      showSalesman: true,
      showCustomer: true,
      showCustomerCity: true,
      showDate: true,
      showInvoiceNo: false,
      dateLabel: "Date",
    },

    columns: {
      labels: [
        { key: "product", label: "Product Name", widthPct: 48 },
        { key: "quantity", label: "Quantity", widthPct: 32 },
        { key: "bonus", label: "Bns", widthPct: 20 },
      ],
      headerSizePx: 9,
      rowSizePx: 10,
      uppercaseHeaders: true,
    },

    groups: {
      groupSizePx: 12,
      showPrefix: true,
      showGroupTotal: true,
      groupTotalLabel: "Total",
    },

    salesman: {
      showSalesmanSection: true,
      sizePx: 11,
      label: "Salesman",
      showSalesmanTotal: true,
      salesmanTotalLabel: "Salesman Total",
    },

    footer: {
      showTotals: true,
      labelSizePx: 11,
      valueSizePx: 12,
      totalLabel: "Total Value",
      bonusLabel: "Bonus Value",
      netLabel: "Net Value",
      valueSuffix: " :-",
      showFootnote: true,
      footnoteText: "Generated by TradeOS",
      footnoteSizePx: 8,
    },

    spacing: {
      salesmanGapPx: 12,
      groupGapPx: 8,
      rowPadYPx: 1,
    },

    boldBody: false,
  },
};

/** Deep clone a default template so custom edits never mutate the shared default. */
export function cloneDefaultTemplate(docType: PrintDocumentType): PrintTemplate {
  return JSON.parse(JSON.stringify(DEFAULT_PRINT_TEMPLATES[docType])) as PrintTemplate;
}

export function defaultTemplateId(docType: PrintDocumentType): string {
  return DEFAULT_PRINT_TEMPLATES[docType].id;
}